In [2]:
import numpy as np

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

In [3]:
A = np.array([[-1, -6], [2, 6]])

In [4]:
def is_eig(A):
    w, v = np.linalg.eig(A)
    print(f'Матрица A:\n{A}')
    print(f'Собственные значения:\n{w}')
    print(f'Собственные векторы:\n{v}')

In [5]:
is_eig(A)

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


2. Дан оператор поворота на 180 градусов, задаваемый матрицей. Показать, что любой вектор является для него собственным.

λ = -1, cправедливо для любого вектора

3. Пусть линейный оператор задан матрицей. Установить, является ли вектор  x=(1,1)  собственным вектором этого линейного оператора.

In [6]:
A = np.array([[1, 1], [-1, 3]])
A

array([[ 1,  1],
       [-1,  3]])

1 + 1 = 1*λ      λ  = 2
-1 + 3 = 1*λ       λ = 2

In [7]:
is_eig(A)

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


Пусть линейный оператор задан матрицей. Установить, является ли вектор x=(3,−3,−4) собственным вектором этого линейного оператора.

-9 = 3*λ    λ = -3
9 = -3*λ    λ = -3
-12 = -4*λ  λ = 3
Вектор x=(3, -3, -4) не является собственным вектором линейного оператора, заданного матрицей A

In [8]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
is_eig(A)

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
